### ISSUE TITLE
home.script.js changing name

### ISSUE THREAD

**Issue by humer2000** [brusselopole/Worldopole#155]
hello folks

i know my question was responeded and closed but am not able to see it again in issues tab

My question was : Is it normal that the file home.scrip.js changes it's name to home.scrip.148565485.js ?
Someone from the coders said yes, it's a linux time stuff.

BUT am hosting this script on Windows 2012R2. 
How to stop this script from changing its name ?

Thanx

**Comment by PoUpA** [comment]
You don't have to worry about it. When the file is loaded timestamp is
added to the name for the client so it is not cached by browser.

Le 21 janv. 2017 16:06, "humer2000" <notifications@github.com> a écrit :

hello folks

i know my question was responeded and closed but am not able to see it
again in issues tab

My question was : Is it normal that the file home.scrip.js changes it's
name to home.scrip.148565485.js ?
Someone from the coders said yes, it's a linux time stuff.

BUT am hosting this script on Windows 2012R2.
How to stop this script from changing its name ?

Thanx

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/brusselopole/Worldopole/issues/155>, or mute the thread

**Comment by Obihoernchen** [comment]
@humer2000 you can see my answer when you click on the closed tab in the issues view. Only the timestamp is called Unix timestamp it works for windows as well. If your site is displayed correctly everything is fine. The server will load it without timestamp. It's just a little hack to automatically update the client browser cache on file changes.

**Comment by humer2000** [comment]
ok... Many thanks for the info.
