### ISSUE TITLE
Pokemon count on home page only rising

### ISSUE THREAD

**Issue by Maveryy** [brusselopole/Worldopole#30]
## Expected Behavior

My pokemon count on the front page is working but the ammount of pokemons is only rising and not decreasing when the pokemon dissapear. The count should update every time a pokemon dissapear.

## Current Behavior

I already have +11k pokemons on my live count and I can guarantee my city doesn't have this ammount of pokemons.

## Possible Solution

I don't know

## Steps to Reproduce (for bugs)

1. You can see my count here http://pokefast.ga
## Your Environment

- Version used: the last one
- URL: http://pokefast.ga
- Operating System and version (desktop or mobile):

**Comment by jipxi** [comment]
Try replacing certain "2 HOURS" with your timezone in other of the php files in core/process/

**Comment by Maveryy** [comment]
I think this may be happening because my PokemonGo-Map is hosted on a server in Spain and I'm trying to use Brazil's timezone? So the "disappear_time" in my DB is different from the "now" var on the website? I'm not sure since I don't know how this works

**Comment by brusselopole** [comment]
It'll require quite a lof of time with the two being on different timezones, will keep in touch

**Comment by NGPriest** [comment]
Mine is stuck on 0...

**Comment by ItsCEED** [comment]
@NGPrist, make sure ur time zone is same as ur pogo map

**Comment by NGPriest** [comment]
@ItsCEED I did, on both Config.php +10 and Variables.php +10 as well as the timezone Australia/Brisbane...

**Comment by ItsCEED** [comment]
Well, best suggestion i can give is to host the site on your vps

**Comment by NGPriest** [comment]
@ItsCEED I'm hosting the site on my local server? :S

**Comment by ItsCEED** [comment]
What the.. thats awkward.. i really dont have a clue

**Comment by AL-dot-debug** [comment]
Hi! 
sorry but we got tons of work :\ 

Your problem is probably due to : 

• server time not sync. 
• server time on a diff timezone than you
• whatever timezone problem. 

I'm working on a fix to not use the mysql NOW() value but a "selected user now() and timezone" witch would be set in variables.json. 

I'll try to finish by the end of the week. 
In the same time, you can try to check your server time and see if it's the same as you describe on your actual variables.json.

**Comment by ghost** [comment]
Hey guys, I think I found a bit more about why a lot of people seem to be reporting issues with times, and it is hard to pinpoint.

I was looking at a few queries, and it seems like most of them are trying to get pokemon information based on the disappear_time, and then some results are thrown out if the dissapear_time is older than NOW(), but that is to cause issues for "new" spawns.

15 minutes should always be substracted from the dissapear_time, otherwise results are going to be off, specially for RARE pokemon. The pokemon will show up on the "latest spawns" list, and then the specific page will say "Last seen: 4 hours"

**Comment by GreenSlime96** [comment]
Hi, I fixed this problem by just using NOW() instead of the more complicated solution in aru.php. I left the JSON just the same as my MySQL database runs in UTC.

**Comment by deivuh** [comment]
Not sure if I should open another issue since this is related. 

I have my counter stuck at 0, same as @NGPriest. 

I used to have an offset of 2 hours which I was able to see in the recently spawn Pokemon detail view; the fresh ones always had "2 hours ago" as last seen. Changed the timezone of the server, pogom server and mysql; now it says "45 minutes ago" for the fresh spawned Pokemon.

**Edit:** ~~Ok, I just changed the config.json timezone from `America/Guatemala` to `Guatemala/America`~~. The Pokemon and lures counter seem to be working now :), though the fresh spawned Pokemon show as last seen 1 hour ago... 

**2nd edit:** Okay, I was just thinking if the 1 hour difference has to do with daylight time savings.  Even though DST doesn't apply here, and the time seems to be correct on both server systems, there may be a part that it's considering GMT-6 as CST. In which CST is currently +1 because of DST. 

**3rd edit:** Found and fixed the problem. The timezone from `variables.json` was never set in `data.loader.php`. Which caused `strtotime` to return an incorrect time if DST is currently applicable in this period but not in the desired country. 

Made a PR to fix this #45 

I'm pretty sure this will fix the related issues too.
@NGPriest is probably having a +1 offset, just like me and that's why all Pokemon have supposedly _despawned_. 
While @Maveryy may have a -1 offset which incorrectly gives an extra _despawning_ hour to all Pokemon and that's why his counter keeps increasing. 

Please confirm :)

**Comment by NGPriest** [comment]
@deivuh My city doesn't use daylight savings... :S

**Comment by AL-dot-debug** [comment]
@deivuh thanks for your fix. 
It was the smartest way to fix it! 

Should fix timezone problem.

**Comment by AL-dot-debug** [comment]
If somes can try with the latest release and let us know if everything's right with it? 
Thanks!

**Comment by deivuh** [comment]
@NGPriest I know, mine doesn't either and that's why we were affected by it. Just try it out and report back if it works :)

@56k-amaury My pleasure 😁

**Comment by NHGRisk** [comment]
i got the same issue and i have no idea on how to fix it
see: http://pokemapoberursel.ddns.net/
i re-setupped everything 3 or 4 times now, always with the latest version (just did an hour ago with the recent one)

**Comment by deivuh** [comment]
@NHGRisk Did you make sure you have the same timezone on your system(s), set "Europe/Berlin" in `timezone` and `time_interval` in _variables.json_?

**Comment by NHGRisk** [comment]
@deivuh yep, Europe/Berlin and +2 hours

> "time_inverval"        : "+2",
> "GMaps_Key"            : "xxx",
> "timezone"                     : "Europe/Berlin",

**Comment by deivuh** [comment]
Try setting it up as +1 in interval, since it is +2 because of DST

## 

David Hsieh

**Comment by AL-dot-debug** [comment]
@NHGRisk could you please on bash give us the result of 

`date`

command on your hosting, and the difference from your local time please?

**Comment by NHGRisk** [comment]
@56k-amaury well, that gives me the following:

> root@PokeOrschel:~# date
> Sun Sep  4 18:49:26 EDT 2016

it should say "Sep 5 00:49"
i've not tried changing the time_interval yet, but it looks like the server timezone is somewhere else
or is it possible to change that ?

Edit:

> root@PokeOrschel:~# sudo date --set 2016-09-05 && date --set 00:53:0
> date: cannot set date: Operation not permitted
> Mon Sep  5 00:00:00 EDT 2016
> root@PokeOrschel:~# date
> Sun Sep  4 18:53:37 EDT 2016

**Comment by AL-dot-debug** [comment]
`sudo dpkg-reconfigure tzdata` may help you (Debian/Ubuntu host) 
Change your timezone to Europe/Berlin and let us know ;)

**Comment by NHGRisk** [comment]
@56k-amaury `date` now shows correct time, restarted apache2 service, still 4600+ pkmn here :/ http://pokemapoberursel.ddns.net/

**Comment by Obihoernchen** [comment]
@NHGRisk please join discord: https://discord.gg/SDvsxkN
It's better for debugging ;)

**Comment by AL-dot-debug** [comment]
There's now an entry about that bug on Wiki. --> https://github.com/brusselopole/Worldopole/wiki/Pokemon-count-on-home-page-is-set-at-0-or-1000 

Please check it first before opening issue about timezone error.
