### ISSUE TITLE
Pokémon Translations in the 'last spawns' list are not applied on new Spawns

### ISSUE THREAD

**Issue by z0n** [brusselopole/Worldopole#81]
## Expected Behavior

On the main page, the 'last spawns' list should apply the translations for the selected language (in my case German) when a new spawn is added.
## Current Behavior

On a page load, the translations are correctly applied. When a new Pokémon spawn is added to the list, it appears with the English name instead of the desired translation.
## Your Environment

- Version used: latest
- URL: https://128bit.org/worldopole/

**Comment by Obihoernchen** [comment]
Mhh looks like we have to add language detection to `core/process/aru.php` as well.

Because currently english is hardcoded, see: https://github.com/brusselopole/Worldopole/blob/master/core/process/aru.php#L154

``` php
$pokelist_file  = SYS_PATH.'/core/json/pokelist_EN.json'; 
$pokemon_file   = file_get_contents($pokelist_file); 
$pokemons       = json_decode($pokemon_file);
```

Maybe we should refactor translation support first. Then we don't have to copy&paste language detection code anymore.

Thank you for reporting!

**Comment by SiteEffect** [comment]
Should we have a look together in the big translation overhaul?
